### ISSUE TITLE
Support Request: How to obtain API Key

### ISSUE THREAD

**Issue by ArmasF31** [donavanbecker/homebridge-meater#1]
### Describe Your Problem

I have not been able to get past the setup. I'm not sure if maybe the developer mode only works on the android app, but there is no Profile tab in the ios app to my knowledge. Can someone tell me how I can get my api key?

### Device & Model

MEATER Plus, ios 17.3

### Node.js Version

v20.10v0

### Homebridge Version

v1.7.0

### Homebridge Meater Plugin Version

v0.1.0-beta.13

### Homebridge UI Version

v4.55.1

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
You shouldn't need any token. Just login with your MEATER account.

Please provide config and logs.

**Comment by donavanbecker** [comment]
@ArmasF31 Were you able to login?
