### ISSUE TITLE
Support Request: adding a device is not working

### ISSUE THREAD

**Issue by akimspin** [donavanbecker/homebridge-meater#11]
### Describe Your Problem

I have added a meater plugin, Im in cooking mode but my meater probe is not found. How to do the proper setup?

### Relevant log output

```shell
[07/07/2024, 00:10:06] [Meater] Loaded homebridge-meater v1.1.1 child bridge successfully
[07/07/2024, 00:10:06] Loaded 0 cached accessories from cachedAccessories.0EA027615C81.
[07/07/2024, 00:10:06] [Meater] Verify Config, Error Message: Email not provided, Submit Bugs Here: https://bit.ly/homebridge-meater-bug-report
[07/07/2024, 00:10:06] Homebridge v1.8.3 (HAP v0.12.2) (Meater) is running on port 33665.
[07/07/2024, 00:10:07] [Meater] Failed to Discover Devices, Error Message: "Cannot read properties of undefined (reading 'token')", Submit Bugs Here: https://bit.ly/homebridge-meater-bug-report
[07/07/2024, 00:10:07] [Meater] Failed to Discover Devices, Error: TypeError: Cannot
```

### Config for homebridge-meater

```shell
{
            "name": "Meater",
            "credentials": {
                "notice": "Keep your tokens a secret!"
            },
            "options": {
                "refreshRate": 60,
                "logging": "standard"
            },
            "_bridge": {
                "username": "0E:A0:27:61:5C:81",
                "port": 33665
            },
            "platform": "Meater"
```

### Device & Model

Iphone 15, Meater plus

### Node.js Version

V18.16.0

### Homebridge Version

v1.8.3

### Homebridge Meater Plugin Version

v1.1.1

### Homebridge UI Version

v4.56.4

### Operating System

Ios

**Comment by akimspin** [comment]
Let me know what more you need.  Thx!

**Comment by donavanbecker** [comment]
Do you have a token inputted?

**Comment by akimspin** [comment]
No. From where I get it? I have tried with instructions but in ios Meater
app there is no token found anywhere

-Mika


su 7.7.2024 klo 0.35 Donavan Becker ***@***.***> kirjoitti:

**Comment by Dylotic** [comment]
Tapping 10 times app version isn't working for me. Any hints?

**Comment by donavanbecker** [comment]
Not sure why you are doing that.

Email and password are required in the config which generates a token.

**Comment by akimspin** [comment]
Do you mean that when registering to meater cloud with email and password the token is generated automatically? Or something else? In any case I have a fully functioning meater app but I am missing a token so please let us know from where the token can be retrieved or regenerated if needed. Thanks!

**Comment by donavanbecker** [comment]
@akimspin I am telling you. It literally says it in your logs, that you are missing your email. And your config doesn't show your email or password in it either. You need to go to the plugins settings and input your email and password.

**Comment by akimspin** [comment]
I have added my meater email and password. My meater is now cooking so it’s connected to my iphone. my logs look like this
![IMG_1276](https://github.com/donavanbecker/homebridge-meater/assets/162810619/e3bbbdf5-04aa-427c-a482-08c29ffb4cfb) so token not provided. Should it be here automatically or am I still doing something wrong? I have done this multiple times during last couple of months with no success. i have other accessories running smoothly over my homebridge but this seem to be a bit trickier to be configured.

**Comment by akimspin** [comment]
When I now look my config editor I have there my email, my password and beside a notice text “Keep your tokens a secret!” but no sign of the token itself.

**Comment by Dylotic** [comment]
I have the same problem. The plugin in asked me for a token I should get from the MEATER app by tapping 10 times on the version number. This isn't working for me.

**Comment by donavanbecker** [comment]
Can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-meater@beta/>=1.1.2-beta.1/orange)](https://www.npmjs.com/package/homebridge-meater)

[Click here to find out how to install Beta](https://github.com/donavanbecker/homebridge-meater/wiki/Beta-Version)

**Comment by akimspin** [comment]
Now finally i have tried a version 1.1.2 but now I get a next error. What to do or what should I do?
![IMG_0716](https://github.com/user-attachments/assets/20ae40f6-5fde-4d0c-8f24-b4cd8023b8fc)
