### ISSUE TITLE
Support Request: Where is my Meater probe token?

### ISSUE THREAD

**Issue by akimspin** [donavanbecker/homebridge-meater#7]
### Describe Your Problem

I’m trying to get my Meater linked to homebridge but I’m just getting an error prompt about missing token. 

### Screenshots

![IMG_1002](https://github.com/donavanbecker/homebridge-meater/assets/162810619/f5ff9d09-7f8b-4a40-8c35-1f0a34ef3be5)

### Device & Model

iphone 15 iOS 17.4

### Node.js Version

18.16.0

### Homebridge Version

1.7.0

### Homebridge Meater Plugin Version

1.1.0

### Homebridge UI Version

4.55.1

### Operating System

Raspbian GNU/Linux Bullseye (11)

**Comment by akimspin** [comment]
Any news on this probe token problem or am I doing something wrong as connecting to Homebridge is not working

**Comment by donavanbecker** [comment]
https://github.com/donavanbecker/homebridge-meater/issues/1#issuecomment-1888063335

The token field is there just in case you need to clear it. It isn't a required field so just populate email and password
